[package]
name = "regions"
version = "0.1.0"
authors = ["Maxim Goncharenko <goncharenko.maxim@apriorit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num="0.2.0"
