[package]
name = "landscape"
version = "0.1.0"
authors = ["Maxim Goncharenko <kacejot@fex.net>"]
edition = "2018"

[lib]
name = "landscape"
path = "src/lib.rs"

[[bin]]
name = "landscape"
path = "src/main.rs"

[dependencies]
num="0.4.3"
rand="0.8.5"
image="0.25.2"
